name: C#

on:
  push:
    branches: [ main ]
    paths:
      - 'cs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cs

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
