name: OCaml

on:
  push:
    branches: [ main ]
    paths:
      - 'ocaml/**'
      - '.github/workflows/ocaml.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ocaml/**'
      - '.github/workflows/ocaml.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ocaml
    steps:
      - uses: actions/checkout@v3
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0
      - run: opam install --deps-only --with-test .
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
