name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - 'rs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'rs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: rs

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
