name: Zig

on:
  push:
    branches: [ main ]
    paths:
      - 'zig/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'zig/**'
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: zig

    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build --verbose
      - run: zig build test --verbose
