name: Zig

on:
  push:
    branches: [ main ]
    paths:
      - 'zig/**'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: zig

    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
      - run: zig build --verbose
